---
- name: add networks
  docker_network:
    name: "{{ docker_network_name }}"
    labels: "{{ docker_network_labels if docker_network_labels is defined else {} }}"
    ipam_driver_options:
      subnet: "{{ docker_network_subnet }}"