---
- name: Add a Single Network
  include_tasks: addnetwork.yml
  when:
    - docker_network_name is defined
    - docker_networks is undefined

- name: Add Multiple Networks
  include_tasks: addnetwork.yml
  loop: "{{ docker_networks if docker_networks is defined else [] }}"
  loop_control:
    loop_var: docker_network_item
  vars:
    docker_network_name: "{{ docker_network_item.docker_network_name }}"
    docker_network_labels: "{{ docker_network_item.docker_network_labels if docker_network_item.docker_network_labels is defined else omit }}"
    docker_network_subnet: "{{ docker_network_item.docker_network_subnet if docker_network_item.docker_network_subnet is defined else None }}"
    docker_network_driver_options: "{{ docker_network_item.driver_options if docker_network_item.driver_options is defined else omit }}"
    docker_network_attachable: "{{ docker_network_item.docker_network_attachable if docker_network_item.docker_network_attachable is defined else omit }}"
    docker_network_driver: "{{ docker_network_item.docker_network_driver if docker_network_item.docker_network_driver is defined else omit }}"
  when:
    - docker_networks is defined
